---
- hosts: servers
  become: true
  tasks: 
    - name: install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "Redhat"
      
    - name: install apache in debian
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      
    - name: apache1
      service: 
        name: httpd
        state: restarted
      when: ansible_os_family == "Redhat"

    - name: apache2
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == "Debian"    

